### ISSUE TITLE
Only version 0.6.0 published to CocoaPods trunk

### ISSUE THREAD

**Issue by johnpatrickmorgan** [kishikawakatsumi/RealmTypeSafeQuery#15]
Hi,

This library looks great, thanks for making it. I can only see `v0.6.0` on [CocoaPods Specs Repo](/CocoaPods/Specs/tree/master/Specs/e/1/d/RealmTypeSafeQuery/0.6.0) - Have you pushed the latest versions to the CocoaPods trunk?

Thanks,
John

**Comment by kishikawakatsumi** [comment]
Thank you for pointed out. I just publish v0.6.1 and v0.7.0. Somehow I forgot to release them.

**Comment by johnpatrickmorgan** [comment]
Great, thanks very much.
